services:
  - type: web
    name: my-ghost-blog
    env: docker
    plan: free
    autoDeploy: true
    buildFilter:
      paths:
        - docker-compose.yml
    disk:
      name: ghost-content
      mountPath: /var/lib/ghost/content
      sizeGB: 1
    envVars:
      - key: url
        value: https://my-ghost-blog.onrender.com
      - key: database__client
        value: sqlite3
      - key: database__connection__filename
        value: /var/lib/ghost/content/data/ghost.db
